### ISSUE TITLE
Nová ikona

### ISSUE THREAD

**Issue by MarhyCZ** [kodi-czsk/plugin.video.ivysilani#14]
Dobrý den,
multimediální centrum je primárně na sledování obsahu, ale taky jeho procházení by mělo být hezkým zážitkem. Napadlo mě redesignovat ikony všech doplňků z tohoto úžasného repozitáře Kodi CZ&SK najednou, aby měli koherentní design, a moderním, hravým vzhledem i vzbudili chuť méně zkušenějším uživatelům je nainstalovat a prozkoumávat :) Návrhy jsem chtěl poslat na jednotlivé github stránky každého doplňku.

Zvolil jsem čtvercová loga, protože průhledná jsou někdy vidět hezky na tmavém skinu a někdy zase jen na světlém. Pozadí je vždy jedna barva či velice lehký gradient. Obsah ikony je vždy 80% na šířku či výšku podle poměru stran. Oficiální wiki Kodi říká, že doplněk by měl mít ikonu 512x512 pixelů, ale to bylo psané v dobách 1080p a když už teď 4K televizory nejsou úplnou raritou, a tyto ikony mají tak jednoduchou grafiku, že mají velice malou velikost na disku, napadlo mě jít rovnou na 1024x1024px.

### Návrhy

Na mém GitHubu se můžete kouknout na ostatní navrhované ikony ve [složce s 2048px návrhy](https://github.com/MarhyCZ/marhycz.github.io/tree/master/kodi-czsk-icons/navrhy)

Případně pár návrhů v jednom obrázku: 
https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/czsknahled.png
_____________________________________________________________________________________________

### Ikona iVysílání
2048px návrh ikony iVysílání je [zde](https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/navrhy/ivysilani.png)

1024px verze ikony iVysílání pro Kodi je [zde](https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/1024/ivysilani.png).

Řídil jsem se podle logotypu České televize a snažil se co nejvíce přiblížit jejich fontu. Na pozadí jsem ani nepřidával žádný gradient, protože ČT dodržuje logotyp a téměř vždy se nachází na bílém pozadí a proto je takto ikona více familiární.

**Comment by jose1711** [comment]
closed via https://github.com/kodi-czsk/plugin.video.ivysilani/pull/17
