### ISSUE TITLE
Přehrávání videa na pozadí při spuštění

### ISSUE THREAD

**Issue by Ryesen** [kodi-czsk/plugin.video.ivysilani#15]
Ahoj,
prosím o opravu nebo radu, jak problém vyřešit.

Když spustím jakýkoliv pořad z iVysilani, tak se začne pořad přehrávat, ale obraz a zvuk nevidím-neslyším. musím v kodi (8.0.2, 17.3) tlačítkem doleva zvolit "Celá obrazovka" aby se obraz zobrazil.

Děkuji za vyřeší, případně za radu.

**Comment by E000001** [comment]
již odstraněno
