### ISSUE TITLE
Nejde přehrát vysílání z OH

### ISSUE THREAD

**Issue by pschonmann** [kodi-czsk/plugin.video.ivysilani#20]
Po zapnutí ČT4 Sport se objeví hláška že mám změnit prohlížeč, nebo nainstalovat Widevine
![screenshot000](https://user-images.githubusercontent.com/6333844/36072371-14d4f87e-0f1f-11e8-804c-1dd2ed3ef9cd.png)

**Comment by E000001** [comment]
Už je po OH, zavírám :D
