### ISSUE TITLE
ČT vysílání posledních několik dnů nefunguje

### ISSUE THREAD

**Issue by jbrepogmailcom** [kodi-czsk/plugin.video.ivysilani#28]
Při pokusu o přístup do knihovny ČT dostávám chybu Err -2  Name or service not known

**Comment by brozikcz** [comment]
Kde presne? Zkusil jsem nahodne par poradu a vsechny mi jdou.

**Comment by jbrepogmailcom** [comment]
Dostanu se na základní přehled jako je Dnes, Nejsledovanější atd. A pak
když bych očekával další úroveň menu přijde ta chyba. Verze 1.3.6,
reinstall nepomohl. Zdá se že při odinstalaci se nemaže konfiguraci, ještě
to bych mohl zkusit.

H.

Dne po 18. 2. 2019 20:26 uživatel brozikcz <notifications@github.com>
napsal:

**Comment by jbrepogmailcom** [comment]
Nainstaloval jsem si iVysilani na druhém počítači a všiml jsem si, že se předtím instaloval nějaký demjson python. V tom bude asi problém, ale nevím, jak ho odinstalovat, abych mohl udělat čistou instalaci, v doplňcích jej nevidím.

**Comment by jbrepogmailcom** [comment]
Tak problém vyřešen, Malině spadl internet...
