### ISSUE TITLE
Plugin přehraje pouze poslední video z playlistu

### ISSUE THREAD

**Issue by jandurovec** [kodi-czsk/plugin.video.ivysilani#3]
U některých pořadů, když je video rozděleno na menší části (třeba soutěžní večery StarDance), plugin přehraje pouze poslední z nich.

Tj. třeba u http://www.ceskatelevize.cz/ivysilani/10570561091-stardance-vii/214522160450006-stardance-vii-kdyz-hvezdy-tanci (tj. StarDance VII, 6. večer) se zobrazí pouze část "Rozhodnutí" (tj video o délce 0:12:39 místo celého večera). U některých jiných večerů (8. večer) je vše OK.

**Comment by StepanOrt** [comment]
Jedná se o chybu na straně ČT. Mobilní aplikace, jejíž API doplněk využívá, pořad ani nepřehraje.
