### ISSUE TITLE
Not possible to use plugin on 18.4 kodi, raspbian buster

### ISSUE THREAD

**Issue by Mikka123T** [kodi-czsk/plugin.video.ivysilani#37]
chybova hlaska: SSL_dh_key_value_too_small SSL c 727

**Comment by aquilegial** [comment]
úplně stejný problém i u mě. Mám Raspberry buster na Raspberry 4.

**Comment by Mikka123T** [comment]
Podarilo sa mi najst riesenie problemu. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788
"The remote site uses a small DH key [0]. If you can't get owner to upgrade the site and want still to access the site I suggest to remove CipherString = DEFAULT@SECLEVEL=2 from /etc/ssl/openssl.cnf."

Cize je potrebne sudo nano /etc/ssl/openssl.cnf a umiestnit "#" pred CipherString = DEFAULT@SECLEVEL=2. Takto #CipherString = DEFAULT@SECLEVEL=2. A uz to ideeee.
