### ISSUE TITLE
Out of memory na Kodi 15.2, OSMC 4.3.0-10-osmc #1 SMP PREEMPT na Raspberry Pi 2

### ISSUE THREAD

**Issue by risa** [kodi-czsk/plugin.video.ivysilani#4]
Zdravím,

při spuštění libovolného videa z iVysilani CT postupně roste využitá paměť, až nakonec systém zatuhne, dokud OOM killer kodi nezabije. Děje se mi to pouze u iVysilani, ale jiné streamovací doplňky nepouživám. Děje se to jak u online vysílání, tak i u archivních pořadů. 

Při běžném pořadu dojde paměť cca po 10 - 12 minutách (1GB RAM), když jsem přidal 500MB swap, tak cca o 10 minut později. Při přehrávání stažených souborů se to neděje. 

Když po cca 8 minutách online vysílání pustím offline video (Avatar Full HD), tak využití paměti zůstává stejné. Neroste, ale ani neklesne:

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
794 osmc      20   0 1024628 529912  24416 S  55.4 70.5 388:48.25 kodi.bin
```

Zkoušel jsem nastavit advancedsettings.xml, zcela zrušit cache ale zdá se že je to jiný problém. Vypadá to, že někde je memory leak. Prosím poradíte mi, jak problém dál diagnostikovat? Je možné že jde o memory leak v ivysilani? Nebo je to problém v Kodi? 

Díky moc.

R.K.

**Comment by lzoubek** [comment]
S dost velkou pravděpodobností se jedná o leak v OSMC. Provozuji ivysilani v Kodi 15.2 na Androidu, x64 linuxu i OpenElec (odroid-c1) a žádné leaky nepozoruji. Tak jako tak, plugin se pouze stará o dodání adresy streamu pro Kodi video player. 

Pokud je to v OSMC možné, zkus pro ivysílání (pravidlem `protocols="http"`) použít [externí player](http://kodi.wiki/view/External_players)

**Comment by risa** [comment]
Na OSMC se mi nepovedlo zprovoznit externí player, tak jsem se pokorně vrátil k Rasbpianu a tam vše funguje jak má. Takže zjevně OSMC bug. Díky za pomoc.
