### ISSUE TITLE
Wrong token exception

### ISSUE THREAD

**Issue by R3gi** [kodi-czsk/plugin.video.ivysilani#40]
Hi, when I try to play something using this addon (v1.3.8) on my Kodi (LibreElec 9.2.1 on Raspberry Pi 3 B+), an error "wrong token" appears and I can't play anything. Everything worked just fine yesterday.

Please, is there any solution? Is it just me?

**Comment by R3gi** [comment]
Photo of log: https://i.ibb.co/cwSsLJQ/IMG-20200415-192538.jpg

**Comment by janlukes** [comment]
Hi,
the token endpoint is returning empty token. Even offical Android app is not working for me, so my best guess is something is just broken CT side and will be OK when CT fixes it.

**Comment by janlukes** [comment]
Check it out now, should be working again.

**Comment by R3gi** [comment]
Indeed, problem has been resolved, both official Android app and this addon fo Kodi are working again. Thank you.
