### ISSUE TITLE
Změna API iVysílání - plugin je zcela nefunkční

### ISSUE THREAD

**Issue by cValda** [kodi-czsk/plugin.video.ivysilani#49]
Od 26.11. 2024 je plugin nefunkční, nezobrazí ani listing, nefunguje live ani zpětné přehrávání.
Patrně kvůli změně API ze strany iVysílání.

**Comment by Samot89** [comment]
Už to jede děkuji👍

**Comment by cValda** [comment]
Nejede, ale existuje nová funkční verze, která je zahrnutá i v repozitáři https://repo.xbmc-kodi.cz/
https://github.com/xbmc-kodi-cz/plugin.video.ivysilani.cz
Tahle verze se už nepoužívá.
