### ISSUE TITLE
Video padá

### ISSUE THREAD

**Issue by zemos8926** [kodi-czsk/plugin.video.ivysilani#5]
Asi po 15minutách se video vypne nebo se mi stalo že se resetuje celý OpenELEC. Čím to je ?

**Comment by StepanOrt** [comment]
@zemos8926 Prosím uveďte více informací (verzi Kodi, verzi OpenElec včetně platformy a případně log). Pravděpodobně se jedná o memory leak v Kodi, který se objevoval i na OSMC, viz. #4.

**Comment by zemos8926** [comment]
dopňuji informace : 
kodi: 15.2, openELEC: 6.0.1(na 6.0 stejný problém) beží na raspberry pi 2
někdy se stává že video se neustále načítá a nejede(při jiných doplňcích/videích žádný problém), kde najít log netuším :)

**Comment by georgeso2** [comment]
Mám také problém na Pi 2 a openELEC 6.0.1. Při přehrávání se po cca 15 minutách malina uplně sekne a je potřeba odpojit napájení. U jiných doplňků se takový problém nevyskytuje.

**Comment by E000001** [comment]
Já to zkoušel na na Rpi2 - OpenElec 6.0.0 mi iVysílání jede v pořádku.

**Comment by zemos8926** [comment]
U mě se sekne i na 6.0.0

**Comment by georgeso2** [comment]
jj na 6.0.0 se mi to také sekalo, po ugradu na 6.0.1 problém stále trvá.

**Comment by E000001** [comment]
a v logu něco máte?

**Comment by zemos8926** [comment]
A kde prosím najdu log

**Comment by sindlarv** [comment]
Mam stejny problem s Raspi Model B rev 2 (000e), OSMC kernel 4.4-1-1.

ivysilani zere pamet, zhruba do 5 minut je konec. V lepsim pripade system sestreli kodi.bin, v horsim zatuhne hardware. Doplnky mam jen od vas (aktualne.cz, befun, ivysilani, pohadkar.cz, soubory online a pak nasa, vimcasts a youtube), vsechny mimo ivysilani jsou ok.

kodi.bin si pri beznem prehravani alokuje (trvale) 105-110 MB pameti (beru RES z toho, co vidim pres top). Pri streamovani z CT pomoci ivysilani se objem alokovane pameti rychle zvysuje az neni kam... logy prikladam, dalsi potrebne doplnim. Staci rict.

[logs.zip](https://github.com/kodi-czsk/plugin.video.ivysilani/files/137079/logs.zip)

**Comment by Baegus** [comment]
+1, na RasPi 2 prakticky nepoužitelné

**Comment by jan-pintr** [comment]
Děje se mi stejný problém. V systémových informacích pěkně vidět jak se paměť postupně zaplňuje až do plna a tedy záseku.

**Comment by georgeso2** [comment]
Včera jsem updatoval OpenELEC na poslední verzi 6.0.3 a zdá se, že problém se tím vyřešil. Při přehrávání dvou pořadů z iVysílání se obsazená paměť držela na 13-14% a k pádu nedošlo.

**Comment by E000001** [comment]
viz. georgeso2
