### ISSUE TITLE
U některých pořadů nelze jít na další stránku 

### ISSUE THREAD

**Issue by soliter26** [kodi-czsk/plugin.video.ivysilani#7]
U některých pořadů nelze jít na další stránku. V doplňku ivysilani najdu pořad pološero, ale je dostupných pouze 24 epizod. Na webu jsou všechny tedy celkem 104 epizod. U pořadu rub a líc je na webu pouze 22 dílů a v doplňku také. Myslím, že se prostě v doplňku nedá načíst další stránka s dalšími díly. Např. u všechnopárty to tlačítko "další" normálně je a u pološera nikoliv. Kodi 16.1, win 10

**Comment by jose1711** [comment]
vyzera, ze z nejakeho dovodu nie je vzdy na stranke rovnaky pocet videi. napravit sa to da napr. tak, ze sa tlacidlo "Next" zobrazi vzdy. v ```addon.py``` treba zmenit
```if len(l) == ivysilani.PAGE_SIZE:```
na
```if len(l) == ivysilani.PAGE_SIZE or True:```
toto ale nie je ozajstna oprava, skor len workaround

**Comment by E000001** [comment]
stránkování je již OK
